apiVersion: v1
kind: Namespace
metadata:
  name: latest-ai-deploy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: latest-ai-deploy-web
  namespace: latest-ai-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latest-ai-deploy-web
  template:
    metadata:
      labels:
        app: latest-ai-deploy-web
    spec:
      containers:
      - name: web
        image: sathyax652/my_ai_app:latest
        ports:
        - containerPort: 8000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: latest-ai-deploy-web
  namespace: latest-ai-deploy
spec:
  selector:
    app: latest-ai-deploy-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort 
