
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latest-ai-deploy-mysql
  namespace: latest-ai-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latest-ai-deploy-mysql
  template:
    metadata:
      labels:
        app: latest-ai-deploy-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: latest-ai-deploy-mysql
  namespace: latest-ai-deploy
spec:
  selector:
    app: latest-ai-deploy-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
